apiVersion: v1
kind: Service
metadata:
  name: mongodb        # This name is CRITICAL. The Python app looks for "mongodb"
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017      # Default Mongo port
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        # Here is the "Senior Engineer" part:
        # We don't type the password here. We point to the Secret.
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: mongo-root-password
